name: Build and Deploy Nextcloud to EC2 via ECR

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout source
      uses: actions/checkout@v3

    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v2
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: ${{ secrets.AWS_REGION }}

    - name: Login to Amazon ECR
      uses: aws-actions/amazon-ecr-login@v1

    - name: Build, Tag and Push Docker image to ECR
      env:
        ECR_REPO: ${{ secrets.ECR_REPO_URI }}
      run: |
        docker build -t nextcloud .
        docker tag nextcloud:latest $ECR_REPO:latest
        docker push $ECR_REPO:latest

    - name: Deploy to EC2 via SSH (no local files)
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.EC2_HOST }}
        username: ec2-user
        key: ${{ secrets.EC2_SSH_KEY }}
        script: |
          aws ecr get-login-password --region ${{ secrets.AWS_REGION }} \
            | docker login --username AWS --password-stdin ${{ secrets.ECR_REPO_URI }}

          docker pull ${{ secrets.ECR_REPO_URI }}:latest

          docker stop nextcloud || true
          docker rm nextcloud || true

          docker run -d --name nextcloud -p 80:80 \
            -e MYSQL_HOST=${{ secrets.RDS_ENDPOINT }} \
            -e MYSQL_DATABASE=${{ secrets.DB_NAME }} \
            -e MYSQL_USER=${{ secrets.DB_USER }} \
            -e MYSQL_PASSWORD=${{ secrets.DB_PASSWORD }} \
            ${{ secrets.ECR_REPO_URI }}:latest

